
[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 1

[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[terminal]
