[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "ComicShannsMonoNerdFont"
style = "Bold"

[font.italic]
family = "ComicShannsMonoNerdFont"
style = "Italic"

[font.normal]
family = "ComicShannsMonoNerdFont"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
opacity = 1

[general]
import = ["~/.config/alacritty/vague.toml"]

[terminal]
