#!/usr/bin/env bash

# Combined script to adjust brightness

# to get this to work with no sudo password, add
# `nicholas ALL=(ALL) NOPASSWD: /usr/bin/light` into the file
# /etc/sudoers.d/sudo_no_password

echo "$(xrandr --verbose)" | grep Bright

case $1 in
    primary)
		sudo light -S $(echo "$(light)" + "$2" | bc)
        ;;
    dual)
    	_val=$(xrandr --verbose | awk '/Bright/ {print $2}' | tail -1)
    	_newval=$(echo "$_val + $2" | bc)
    	xrandr --output HDMI-1-0 --brightness $_newval
        ;;
    *)
        echo "Usage: $0 {up|down}"
        exit 1
esac
