#!/usr/bin/env bash

if [[ "${XDG_SESSION_TYPE}" == "x11" ]]; then
	setxkbmap -option ctrl:nocaps &
	picom --experimental-backends --backend glx --xrender-sync-fence &
	xinput set-prop 11 "libinput Natural Scrolling Enabled" 1
	${HOME}/.config/qtile/scripts/refresh-monitors-x11 &

elif [[ "${XDG_SESSION_TYPE}" == "wayland" ]]; then
	${HOME}/.config/qtile/scripts/refresh-monitors-wayland &
fi

${HOME}/.config/qtile/scripts/battery-check &
