#!/usr/bin/env bash

if [[ "${XDG_SESSION_TYPE}" == "x11" ]]; then
	setxkbmap -option ctrl:nocaps &
	picom --experimental-backends --backend glx --xrender-sync-fence &
	xinput set-prop 11 "libinput Natural Scrolling Enabled" 1
fi

${HOME}/.config/qtile/scripts/battery-check &

${HOME}/.config/qtile/scripts/refresh-monitors &
