#!/usr/bin/env bash

PORT_NAME=$1

if [[ -z $PORT_NAME ]]; then
    PORT_NAME="HDMI-1-0"
fi

xrandr --output ${PORT_NAME} --off

MONITOR_STATUS=$(xrandr | awk "/${PORT_NAME}/ {print \$2}")

if [ "$MONITOR_STATUS" = "connected" ]; then
    xrandr --output ${PORT_NAME} --auto
    xrandr --output ${PORT_NAME} --noprimary --above eDP-1
fi

feh --no-fehbg --bg-scale ${HOME}/.config/qtile/assets/house-on-river.jpg

# rosepint
# xsetroot -solid '#191724'

# vague
# xsetroot -solid '#141415'


# nvim default
# xsetroot -solid "#14161b"
#----------
