#!/usr/bin/env bash

# Parse args
while [[ $# -gt 0 ]]; do
	case $1 in
		--which-pip )
			PIP=$2
			shift 2
			;;
		* )
			shift
			;;
	esac
done

# Check if PIP is set
if [[ -z "$PIP" ]]; then
	echo "Error: No pip specified. Use: which-pip <pip_path>"
	exit 1
fi

echo "Using pip: $PIP"

# Install Python packages
"$PIP" install ruff pyright

# Install npm packages
npm install -g \
	bash-language-server \
	vim-language-server
