shell:
  program: /bin/bash
  args:
    - --login

env:
  TERM: xterm-256color

window: 
  opacity: 1

font:
  normal:
    family: 'UbuntuMono Nerd Font'
    style: Regular

  bold:
    family: 'UbuntuMono Nerd Font'
    style: Bold

  italic:
    family: 'UbuntuMono Nerd Font'
    style: Italic

  size: 10

import:
  - ~/.config/alacritty/rose-pine.yml
