#!/usr/bin/env python3

import re
import subprocess
from typing import Optional


class DualMonitorBrightness:
    def __init__(self):
        self._dual_monitors = None

    @property
    def dual_monitors(self):
        if self._dual_monitors is None:
            self._dual_monitors = self._refresh_dual_monitors()
        return self._dual_monitors

    def increment(self, value: int, monitor_id: Optional[int] = None, 
                  bus_id: Optional[int] = None):
        monitor_id, bus_id = self._get_monitor_id_and_bus_id(
            monitor_id=monitor_id, bus_id=bus_id
        )
        current = self.get(monitor_id=monitor_id)
        new = current + value
        self.set(value=new, monitor_id=monitor_id)
        return None

    def get(self, monitor_id: Optional[int] = None, bus_id: Optional[int] = None):
        _, bus_id = self._get_monitor_id_and_bus_id(
            monitor_id=monitor_id, bus_id=bus_id
        )
        return self._get(bus_id)

    def set(self, value: int, monitor_id: Optional[int] = None,
                  bus_id: Optional[int] = None):
        monitor_id, bus_id = self._get_monitor_id_and_bus_id(
            monitor_id=monitor_id, bus_id=bus_id
        )
        self._set(value=value, bus_id=bus_id, monitor_id=monitor_id)
        return None

    def _refresh_dual_monitors(self):
        detect = subprocess.run(
            "ddcutil detect", shell=True, stdout=subprocess.PIPE
        ).stdout.decode().split("\n")
        active_displays = {}
        for line in detect:
            display = re.match(r'^(Display)\s([0-9]).*', line)
            if display:
                active_displays[int(display.group(2))] = {}
            elif len(active_displays.keys()) > 0:
                current_key = list(active_displays.keys())[-1]
                bus_id = re.match(r'^\s*(I2C\sbus:).*-([0-9]*$)', line)
                if bus_id:
                    active_displays[current_key]["bus_id"] = int(bus_id.group(2))
                    active_displays[current_key]["brightness"] = self._get(
                        bus_id=int(bus_id.group(2))
                    )
                serial = re.match(r'^\s*(Serial\snumber:)\s*(\S*$)', line)
                if serial:
                    active_displays[current_key]["serial"] = serial.group(2)
                model = re.match(r'^\s*(Model:)', line)
                if model:
                    active_displays[current_key]["model"] = " ".join(line.split()[1:])
        return active_displays

    def _get(self, bus_id: int):
        result = subprocess.run(
            f"ddcutil --bus={bus_id} getvcp 10",
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        if len(result.stderr.decode()) > 0:
            raise Exception(result.stderr.decode())
        current = re.match(
            r'^.*(current\svalue\s=)\s*([0-9]*).*',
            result.stdout.decode()
        )
        if current is not None:
            return int(current.group(2))
        else:
            raise Exception("get didnt work")

    def _set(self, value: int, bus_id: int, monitor_id: int):
        if value > 100:
            value = 100
        elif value < 0:
            value = 0
        result = subprocess.run(
            f"ddcutil --bus={bus_id} setvcp 10 {value}",
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        if len(result.stderr.decode()) > 0:
            raise Exception(f"{result.stderr.decode()}")
        self.dual_monitors[monitor_id]["brightness"] = value
        return None

    def _get_monitor_id_and_bus_id(self, monitor_id: Optional[int] = None,
                  bus_id: Optional[int] = None):
        if monitor_id is None and bus_id is None:
            raise NotImplementedError("enter a monitor_id or bud_id")

        if monitor_id is not None and monitor_id not in self.dual_monitors:
            self._dual_monitors = self._refresh_dual_monitors()
            if monitor_id not in self.dual_monitors:
                raise KeyError("monitor_id not found")

        if monitor_id is None:
            for id in self.dual_monitors:
                if "bus_id" in self.dual_monitors[id]:
                    if self.dual_monitors[id]["bus_id"] == bus_id:
                        monitor_id = int(id)

            if monitor_id is None:
                self._dual_monitors = self._refresh_dual_monitors()

            for id in self.dual_monitors:
                if "bus_id" in self.dual_monitors[id]:
                    if self.dual_monitors[id]["bus_id"] == bus_id:
                        monitor_id = int(id)

            if monitor_id is None:
                raise Exception("monitor_id not found for bus_id")

        if bus_id is None:
            bus_id = int(self.dual_monitors[monitor_id]["bus_id"])
        else:
            raise Exception("asdf")

        return monitor_id, bus_id


x = DualMonitorBrightness()
x.dual_monitors
x.set(25, 1)
x._refresh_dual_monitors()
